//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2020.04.17 at 05:00:20 PM IDT 
//


package data.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}MapDescriptor"/&gt;
 *         &lt;element ref="{}PlannedTrips" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mapDescriptor",
    "plannedTrips"
})
@XmlRootElement(name = "TransPool")
public class TransPool {

    @XmlElement(name = "MapDescriptor", required = true)
    protected MapDescriptor mapDescriptor;
    @XmlElement(name = "PlannedTrips")
    protected PlannedTrips plannedTrips;

    /**
     * Gets the value of the mapDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link MapDescriptor }
     *     
     */
    public MapDescriptor getMapDescriptor() {
        return mapDescriptor;
    }

    /**
     * Sets the value of the mapDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapDescriptor }
     *     
     */
    public void setMapDescriptor(MapDescriptor value) {
        this.mapDescriptor = value;
    }

    /**
     * Gets the value of the plannedTrips property.
     * 
     * @return
     *     possible object is
     *     {@link PlannedTrips }
     *     
     */
    public PlannedTrips getPlannedTrips() {
        return plannedTrips;
    }

    /**
     * Sets the value of the plannedTrips property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlannedTrips }
     *     
     */
    public void setPlannedTrips(PlannedTrips value) {
        this.plannedTrips = value;
    }

}
